workflows:
  ios-build:
    name: iOS Build
    max_build_duration: 120
    instance_type: mac_mini_m1
    environment:
      flutter: stable
    working_directory: .
    scripts:
      - flutter pub get
      - flutter build ios --release --no-codesign
    artifacts:
      - build/ios/iphoneos/*.ipa