workflows:
  ios-release:
    name: iOS Release Build
    environment:
      flutter: stable
      ios_signing:
        provisioning_profiles:
          - path: "RevLogPro.mobileprovision"
    scripts:
      - flutter build ipa --release
    artifacts:
      - build/ios/ipa/*.ipa





