workflows:
  android-release:
    name: Android Release Build
    environment:
      flutter: stable
    scripts:
      - flutter pub get
      - flutter build apk --release --no-tree-shake-icons
    artifacts:
      - build/**/outputs/**/*.apk

  workflows:
  ios-release:
    name: iOS Release Build
    environment:
      flutter: stable
      groups:
        - apple-credentials
      vars:
        BUNDLE_ID: "com.lukedipaola.revlogpro"
      ios_signing:
        distribution_type: app_store
        bundle_identifier: "com.lukedipaola.revlogpro"
    scripts:
      - flutter pub get
      - flutter build ipa --release --no-tree-shake-icons
    artifacts:
      - build/ios/ipa/*.ipa
    # No publishing block





